export const getRecipeReducer = [{
    "vegetarian": false,
    "vegan": false,
    "glutenFree": false,
    "dairyFree": true,
    "veryHealthy": false,
    "cheap": false,
    "veryPopular": false,
    "sustainable": false,
    "weightWatcherSmartPoints": 9,
    "gaps": "no",
    "lowFodmap": false,
    "aggregateLikes": 3,
    "spoonacularScore": 74,
    "healthScore": 29,
    "pricePerServing": 560.51,
    "extendedIngredients": [
      {
        "id": 15001,
        "aisle": "Seafood",
        "image": "fresh-anchovies.jpg",
        "consistency": "solid",
        "name": "anchovies",
        "original": "1lb of anchovies cleaned, spine removed",
        "originalString": "1lb of anchovies cleaned, spine removed",
        "originalName": "anchovies cleaned, spine removed",
        "amount": 1,
        "unit": "lb",

      },
      {
        "id": 18371,
        "aisle": "Baking",
        "image": "white-powder.jpg",
        "consistency": "solid",
        "name": "baking powder",
        "original": "1 teaspoon of baking powder",
        "originalString": "1 teaspoon of baking powder",
        "originalName": "baking powder",
        "amount": 1,
        "unit": "teaspoon",
      },
      {
        "id": 1123,
        "aisle": "Milk, Eggs, Other Dairy",
        "image": "egg.png",
        "consistency": "solid",
        "name": "egg",
        "original": "1 egg",
        "originalString": "1 egg",
        "originalName": "egg",
        "amount": 1,
        "unit": "",
      },
      {
        "id": 20081,
        "aisle": "Baking",
        "consistency": "solid",
        "name": "flour",
        "original": "1 cup of flour",
        "originalString": "1 cup of flour",
        "originalName": "flour",
        "amount": 1,
        "unit": "cup",

      },
      {
        "originalString": "sage leaves (optional - if you are not a fan of sage just omit)"
      },
      {
        "originalString": "1 teaspoon of salt",
      },
      {
        "originalString": "seltzer water",
      },
      {
        "originalString": "vegetable oil for frying",
      }
    ],
    "id": 1,
    "title": "Fried Anchovies with Sage",
    "readyInMinutes": 45,
    "servings": 3,
    "image": "https://spoonacular.com/recipeImages/221397-556x370.jpg",
    "imageType": "jpg",
    "summary": 'Fried Anchovies with Sage might be just the main course you are searching for. One portion of this dish contains roughly <b>37g of protein</b>, <b>11g of fat</b>, and a total of <b>384 calories</b>. This recipe serves 3 and costs $5.61 per serving. Head to the store and pick up anchovies, sage leaves, seltzer water, and a few other things to make it today. To use up the baking powder you could follow this main course with the <a href="https://spoonacular.com/recipes/simple-raspberry-lemon-cake-671414">Simple Raspberry Lemon Cake</a> as a dessert. 2 people have tried and liked this recipe. From preparation to the plate, this recipe takes approximately <b>45 minutes</b>. With a spoonacular <b>score of 73%</b>, this dish is good. Try <a href="https://spoonacular.com/recipes/fried-sage-with-anchovies-493285">Fried Sage With Anchovies</a>, <a href="https://spoonacular.com/recipes/veal-shanks-with-olives-anchovies-and-sage-597839">Veal Shanks with Olives, Anchovies, and Sage</a>, and <a href="https://spoonacular.com/recipes/homemade-spaghetti-with-shallots-sage-lemons-anchovies-568523">Homemade Spaghetti with Shallots, Sage, Lemons & Anchovies</a> for similar recipes.',
    "dishTypes": [
      "lunch",
      "main course",
      "main dish",
      "dinner",
    ],
    "diets": [
      "dairy free",
      "pescatarian",
    ],
    "instructions": "<p>If you have not tried anchovies before - you must try them now! Get over any weird apprehensions or that its just bait or a punchline for a joke about pizza ('extra anchovies')! These little suckers are delicious &amp; actually good for you! Baked, fried &amp; grilled - they are ohh so good and worth a try. If your not up to it, then pass me your plate because I love'em!Here is my favorite - Fried Anchovies - the recipe below adds a sage leave to each piece of fish as well for an extra burst of flavor &amp; color.Fried Anchovies with SageAcciughe fritte con Salvia1lb of anchovies cleaned, spine removedsage leaves (optional - if you are not a fan of sage just omit)batter1 cup of flour1 egg1 teaspoon of salt1 teaspoon of baking powderseltzer watervegetable oil for fryingIn a bowl combine flour, eggs, salt &amp; baking powder. Slowly add in seltzer water &amp; mix until forms a thin batter. Cover with plastic &amp; set in the fridge for at least an hour.Heat oil in a pot to 350 degree.Remove batter from fridge and mix once or twice (batter will have separated).Take a sage leaf &amp; anchovy put them together &amp; dip into the batter - allowing access batter to drip off.Fry 20 seconds a side until golden brown.Remove from oil &amp; drain on a paper towel.Sprinkle with salt &amp; serve immediately.Pairs great with prosecco or white wine.</p>",
    "analyzedInstructions": [
      {
        "name": "",
        "steps": [
          {
            "id": 1,
            "number": 1,
            "step": "If you have not tried anchovies before - you must try them now! Get over any weird apprehensions or that its just bait or a punchline for a joke about pizza ('extra anchovies')! These little suckers are delicious &amp; actually good for you!",
            "ingredients": [
              {
                "id": 15001,
                "name": "anchovies",
                "localizedName": "anchovies",
              },
              {
                "id": 0,
                "name": "lollipops",
                "localizedName": "lollipops",
              },
            ],
          },
          {
            "id": 2,
            "number": 2,
            "step": "Baked, fried &amp; grilled - they are ohh so good and worth a try. If your not up to it, then pass me your plate because I love'em!Here is my favorite - Fried Anchovies - the recipe below adds a sage leave to each piece of fish as well for an extra burst of flavor &amp; color.Fried Anchovies with Sage",
            "ingredients": [{
              "id": 15001,
              "name": "anchovies",
              "localizedName": "anchovies",
            },
            {
              "id": 10115261,
              "name": "fish",
              "localizedName": "fish",
            },
            {
              "id": 99226,
              "name": "sage",
              "localizedName": "sage",
            },
            ],

          },
          {
            "id": 3,
            "number": 3,
            "step": "Acciughe fritte con Salvia1lb of anchovies cleaned, spine removedsage leaves (optional - if you are not a fan of sage just omit)batter1 cup of flour1 egg1 teaspoon of salt1 teaspoon of baking powderseltzer watervegetable oil for frying",
            "ingredients": [
              {
                "id": 15001,
                "name": "anchovies",
                "localizedName": "anchovies",
              },
              {
                "id": 99226,
                "name": "sage",
                "localizedName": "sage",
              },
              {
                "name": "cooking oil",
                "localizedName": "cooking oil",
              },
            ],
          },
          {
            "id": 4,
            "number": 4,
            "step": "In a bowl combine flour, eggs, salt &amp; baking powder. Slowly add in seltzer water &amp; mix until forms a thin batter. Cover with plastic &amp; set in the fridge for at least an hour.",
            "ingredients": [
              {
                "id": 18369,
                "name": "baking powder",
                "localizedName": "baking powder",
              },
              {
                "id": 14121,
                "name": "sparkling water",
                "localizedName": "sparkling water",
              },
              {
                "id": 20081,
                "name": "all purpose flour",
                "localizedName": "all purpose flour",
              },
              {
                "id": 1123,
                "name": "egg",
                "localizedName": "egg",
              },
              {
                "id": 2047,
                "name": "salt",
                "localizedName": "salt",
              },
            ],
          },
          {
            "id": 5,
            "number": 5,
            "step": "Heat oil in a pot to 350 degree.",
            "ingredients": [
              {
                "id": 4582,
                "name": "cooking oil",
                "localizedName": "cooking oil",
              },
            ],
            "equipment": [
              {
                "id": 404752,
                "name": "pot",
                "localizedName": "pot",
              },
            ],
          },
          {
            "id": 6,
            "number": 6,
            "step": "Remove batter from fridge and mix once or twice (batter will have separated).Take a sage leaf &amp; anchovy put them together &amp; dip into the batter - allowing access batter to drip off.Fry 20 seconds a side until golden brown.",
            "ingredients": [
              {
                "id": 15001,
                "name": "anchovies",
                "localizedName": "anchovies",
                "image": "anchovies.jpg",
              },
              {
                "id": 99226,
                "name": "sage",
                "localizedName": "sage",
              },
              {
                "id": 0,
                "name": "dip",
                "localizedName": "dip",
              },
            ],

          },
          {
            "id": 7,
            "number": 7,
            "step": "Remove from oil &amp; drain on a paper towel.",
            "ingredients": [
              {
                "id": 4582,
                "name": "cooking oil",
                "localizedName": "cooking oil",
              },
            ],
            "equipment": [
              {
                "id": 405895,
                "name": "paper towels",
                "localizedName": "paper towels",
              },
            ],
          },
          {
            "id": 8,
            "number": 8,
            "step": "Sprinkle with salt &amp; serve immediately.Pairs great with prosecco or white wine.",
            "ingredients": [
              {
                "id": 14106,
                "name": "white wine",
                "localizedName": "white wine",
              },
              {
                "id": 0,
                "name": "prosecco",
                "localizedName": "prosecco",
              },
              {
                "id": 2047,
                "name": "salt",
                "localizedName": "salt",
              },
            ],

          },
        ],
      },
    ],

  },
  {
    vegetarian: false,
    vegan: false,
    glutenFree: false,
    dairyFree: true,
    veryHealthy: false,
    cheap: false,
    veryPopular: true,
    sustainable: false,
    weightWatcherSmartPoints: 12,
    gaps: 'no',
    lowFodmap: false,
    preparationMinutes: 15,
    cookingMinutes: 0,
    aggregateLikes: 970,
    spoonacularScore: 78,
    healthScore: 11,
    creditsText: 'Deep South Dish',
    sourceName: 'Deep South Dish',
    pricePerServing: 129.24,
    extendedIngredients: [
      {
        id: 1253,
        aisle: 'Cheese',
        image: 'american-cheese.jpg',
        consistency: 'solid',
        name: 'american cheese',
        original: '1 slice of American cheese',
        originalString: '1 slice of American cheese',
        originalName: 'American cheese',
        amount: 1,
        unit: 'slice',
        meta: [],
        metaInformation: [],
        measures: [Object]
      },
      {
        id: 10862,
        aisle: 'Meat',
        image: 'cooked-bacon.jpg',
        consistency: 'solid',
        name: 'cooked bacon',
        original: '2-3 slices of bacon, cooked crisp',
        originalString: '2-3 slices of bacon, cooked crisp',
        originalName: 'bacon, cooked crisp',
        amount: 2,
        unit: 'slices',
        meta: [Array],
        metaInformation: [Array],
        measures: [Object]
      },
      {
        id: 1123,
        aisle: 'Milk, Eggs, Other Dairy',
        image: 'egg.png',
        consistency: 'solid',
        name: 'egg',
        original: '1 egg, fried',
        originalString: '1 egg, fried',
        originalName: 'egg, fried',
        amount: 1,
        unit: '',
        meta: [],
        metaInformation: [],
        measures: [Object]
      },
      {
        id: 11252,
        aisle: 'Produce',
        image: 'iceberg-lettuce.jpg',
        consistency: 'solid',
        name: 'lettuce',
        original: 'Lettuce',
        originalString: 'Lettuce',
        originalName: 'Lettuce',
        amount: 1,
        unit: 'serving',
        meta: [],
        metaInformation: [],
        measures: [Object]
      },
      {
        id: 4025,
        aisle: 'Condiments',
        image: 'mayonnaise.png',
        consistency: 'liquid',
        name: 'mayonnaise',
        original: 'Mayonnaise',
        originalString: 'Mayonnaise',
        originalName: 'Mayonnaise',
        amount: 1,
        unit: 'serving',
        meta: [],
        metaInformation: [],
        measures: [Object]
      },
      {
        id: 11529,
        aisle: 'Produce',
        image: 'tomato.png',
        consistency: 'solid',
        name: 'tomato',
        original: '1-2 slices of tomato',
        originalString: '1-2 slices of tomato',
        originalName: 'tomato',
        amount: 1,
        unit: 'slices',
        meta: [],
        metaInformation: [],
        measures: [Object]
      },
      {
        id: 18069,
        aisle: 'Bakery/Bread',
        image: 'white-bread.jpg',
        consistency: 'solid',
        name: 'white bread',
        original: '2 slices of bread, white or wheat',
        originalString: '2 slices of bread, white or wheat',
        originalName: 'bread, white or wheat',
        amount: 2,
        unit: 'slices',
        meta: [Array],
        metaInformation: [Array],
        measures: [Object]
      }
    ],
    id: 243988,
    title: 'Fried Egg BLT Sandwich',
    readyInMinutes: 15,
    servings: 1,
    sourceUrl: 'http://www.deepsouthdish.com/2009/04/fried-egg-blt-sandwich.html',
    image: 'https://spoonacular.com/recipeImages/243988-556x370.jpg',
    imageType: 'jpg',
    summary: 'Fried Egg BLT Sandwich is a <b>dairy free</b> main course. For <b>$1.65 per serving</b>, this recipe <b>covers 20%</b> of your daily requirements of vitamins and minerals. One portion of this dish contains approximately <b>21g of protein</b>, <b>33g of fat</b>, and a total of <b>501 calories</b>. This recipe serves 1. This recipe is liked by 970 foodies and cooks. Head to the store and pick up mayonnaise, bacon, tomato, and a few other things to make it today. To use up the mayonnaise you could follow this main course with the <a href="https://spoonacular.com/recipes/super-peanut-butter-brownies-made-lighter-113420">Super! Peanut Butter Brownies Made Lighter</a> as a dessert. All things considered, we decided this recipe <b>deserves a spoonacular score of 78%</b>. This score is good. Try <a href="https://spoonacular.com/recipes/healthy-egg-salad-sandwich-913169">Healthy Egg Salad Sandwich</a>, <a href="https://spoonacular.com/recipes/blt-salad-917813">BLT Salad</a>, and <a href="https://spoonacular.com/recipes/blt-salad-916021">BLT Salad</a> for similar recipes.',
    cuisines: [],
    dishTypes: [ 'lunch', 'main course', 'main dish', 'dinner' ],
    diets: [ 'dairy free' ],
    occasions: [],
    winePairing: {},
    instructions: null,
    analyzedInstructions: [],
    originalId: null
  }
  ]